# TLS listener on port 8883
listener 8883 127.0.0.1
bind_address localhost
cafile certs/ca.pem
certfile certs/server.pem
keyfile certs/server-key.pem
require_certificate true
use_identity_as_username true
allow_anonymous false
log_type all
log_dest stdout